### ISSUE TITLE
Have you tried to stream video?

### ISSUE THREAD

**Issue by shahriarhossain** [maheshpatil132/zoom-clone#1]
It looks like the current code only shows the user video stream on the screen and when a second user joins the meeting, it console log that information. But it doesn't stream video.

**Comment by maheshpatil132** [comment]
Hey, 👋

Thanks for taking interest in this project.

The issue was in socket.io client,

Socket io client has update their version and  also make changes in their
policy

Now , the issue is solved

Thanks
Mahesh Patil

**Comment by shahriarhossain** [comment]
Thanks for your quick response. Socket io is working, it successfully log message each time a new user join or left the room. 

However, it doesn't show the remote video stream! 

I just tried your app from two different machine at the same time. 
https://zoom-videochatapp.netlify.app/user1/4yIy0_QAaZj8HNG7AABD
https://zoom-videochatapp.netlify.app/user2/4yIy0_QAaZj8HNG7AABD
It only shows current user's video stream on the screen, not the remote video stream! 

Looking at the code, I found you only have one video element where you are setting your own video source, instead of the remote video source. 
`<video muted={true} autoPlay={true} ref={myvideo}></video>`

**Comment by maheshpatil132** [comment]
Yes, Sometimes the Remote video stream is not shown, But  after rejoining it works fine,

I have tested the Project and in my case, it works well even I also sent the link to my friends and that time also it works well.

I request that you please try once again time and let me know about your experience,

And lastly your Query about the Remote video stream element,

Ans)  The Remote Video stream element is created and append in div by the plain javascript,

` const video = document.createElement('video')`

Append Function

`

    const append = (video, stream, name) => {

        video.srcObject = stream;
        const div = document.createElement('div');
        const h1 = document.createElement('h1');
        h1.classList.add('text-3xl', 'text-center', 'absolute', 'capitalize');

        video.addEventListener('loadedmetadata', () => {
            video.play();
        })

        h1.textContent = name;
        div.classList.add('border', 'rounded', 'overflow-hidden', 'bg-slate-400', 'overflow-hidden', 'relative', 'h-fit');
        div.appendChild(h1);
        div.appendChild(video);
        mydiv.current.appendChild(div);
        RemoveUnusedDivs();}`


I hope your all queries are  solved, Let me know if you face any problem,

Thanks for tacking an interest in the Project!

**Comment by shahriarhossain** [comment]
Thanks for your quick response. I have tried with the live link [zoom-videochatapp.netlify.app](https://zoom-videochatapp.netlify.app/) from two different computer.
Here is the step I perform:
From PC1
1. visited [zoom-videochatapp.netlify.app](https://zoom-videochatapp.netlify.app/)
2. Clicked Create Meeting
3. Copy the Meeting Id
4. Enter Name : Person1
5. Enter Code : typed the Meeting Id got from step 3
6. Join Meeting

From PC2:
1. visited [zoom-videochatapp.netlify.app](https://zoom-videochatapp.netlify.app/)
2. Enter Name : Person2
3. Enter Code : typed the Meeting Id generated by PC1 in step 2
4. Join Meeting

From both PC, only can see current video stream. 

Have also tried to disconnect from PC2 and then tried to re-connect with the steps above. Still not seeing any remote stream.

**Comment by maheshpatil132** [comment]
![2023-05-21](https://github.com/maheshpatil132/zoom-clone/assets/92781925/7787855c-45c1-4ea6-8934-4b78bed4ce7b)
![2023-05-21 (2)](https://github.com/maheshpatil132/zoom-clone/assets/92781925/37fcd545-c2e1-4d8f-87b9-e23c0f798d4f)

can you share the Screenshot?
